### ISSUE TITLE
During any async process running, the dialog form should not disapper if user touches other part of JupyterLab

### ISSUE THREAD

**Issue by pacospace** [thoth-station/jupyterlab-requirements#111]
**Describe the bug**
During any async process running, the dialog form should not disapper if user touches other part of JupyterLab.

**To Reproduce**
1. Start any async process in the UI
2. Touch screen out of dialog form

**Expected behavior**
The dialog form does not disappear

**Screenshots**

**Additional context**

**Comment by pacospace** [comment]
@Gkrumbach07 what about this issue? wdyt?

**Comment by Gkrumbach07** [comment]
> @Gkrumbach07 what about this issue? wdyt?

Is there a specific process? For testing purposes.

**Comment by pacospace** [comment]
> > @Gkrumbach07 what about this issue? wdyt?
> 
> Is there a specific process? For testing purposes.

The test should be: when you open the dependency management UI and then you click outside of it, the UI will disappear even if a process is running.

**Comment by Gkrumbach07** [comment]
story point: 3
