### ISSUE TITLE
configure timeout for thoth resolution engine

### ISSUE THREAD

**Issue by pacospace** [thoth-station/jupyterlab-requirements#184]

**Comment by fridex** [comment]
If you wait for the advise results using thamos library, you can reuse `THAMOS_TIMEOUT`. Thamos automatically terminates the request if it took too long to complete [1].

https://github.com/thoth-station/jupyterlab-requirements/blob/5b9869963429a9810a545a57b2980ed5b921e2bb/jupyterlab_requirements/dependency_management/thoth.py#L88

[1] https://github.com/thoth-station/thamos#using-thoth-and-thamos-in-openshifts-s2i

**Comment by pacospace** [comment]
> If you wait for the advise results using thamos library, you can reuse `THAMOS_TIMEOUT`. 
> 
> https://github.com/thoth-station/jupyterlab-requirements/blob/5b9869963429a9810a545a57b2980ed5b921e2bb/jupyterlab_requirements/dependency_management/thoth.py#L88
> 
> [1] https://github.com/thoth-station/thamos#using-thoth-and-thamos-in-openshifts-s2i

So I can set `THAMOS_TIMEOUT` to something like 120s? sounds reasonable? @fridex 

> Thamos automatically terminates the request if it took too long to complete [1].

```
2021-03-11 18:02:22,405 [25759] WARNING  jupyterlab_requirements.thoth: error talking to Thoth: Thoth backend did not respond in time, timeout set to 2000 - see https://thoth-station.ninja/j/thamos_timeout
```
I did not configure the env yet

**Comment by pacospace** [comment]
> > If you wait for the advise results using thamos library, you can reuse `THAMOS_TIMEOUT`.
> > https://github.com/thoth-station/jupyterlab-requirements/blob/5b9869963429a9810a545a57b2980ed5b921e2bb/jupyterlab_requirements/dependency_management/thoth.py#L88
> > 
> > [1] https://github.com/thoth-station/thamos#using-thoth-and-thamos-in-openshifts-s2i
> 
> So I can set `THAMOS_TIMEOUT` to something like 120s? sounds reasonable? @fridex
> 
> > Thamos automatically terminates the request if it took too long to complete [1].
> 
> ```
> 2021-03-11 18:02:22,405 [25759] WARNING  jupyterlab_requirements.thoth: error talking to Thoth: Thoth backend did not respond in time, timeout set to 2000 - see https://thoth-station.ninja/j/thamos_timeout
> ```
> 
> I did not configure the env yet

@fridex can we have `timeout` parameter in `advise_using_config` method?

**Comment by pacospace** [comment]
@fridex @goern do we want to allow users to modify a default value? Maybe we set to 2 min by default, as with https://github.com/thoth-station/thoth-application/issues/1112 they might receive it immediately if it is known? Moreover even if it times out we still collect the adviser report and we can see what stacks are requested and if pipenv was used, we can add https://github.com/thoth-station/jupyterlab-requirements/issues/203 saying the stack might not be optimized please relock if you want to receive an optimized stuck for your enviornment.
