### ISSUE TITLE
Do not recreate kernel every time but just relock without stopping and restarting the kernel

### ISSUE THREAD

**Issue by pacospace** [thoth-station/jupyterlab-requirements#220]
**Describe the bug**
If I'm working on my notebook and I want to add a new dependency, currently the kernel is recreated and restarted. This means all variables are lost and the notebook need to run again from the beginning. This behaviour can be not nice.

**To Reproduce**
1. Work on your notebook and add a new depnedency
2. Run a cell alrady run and imports are not yet run.

**Expected behavior**
For an existing kernel already used by the notebook, do not recreate it, rather install the dependency and allow user to continue to work. If the dependencies are installed in a kernel different from the one where the user is working, then recreate the environment.

**Screenshots**

**Additional context**

**Comment by goern** [comment]
is this still valid?

/kind feature

**Comment by pacospace** [comment]
> is this still valid?
> 
> /kind feature

Yes this one should be done soon!
