### ISSUE TITLE
Dependencies found in notebook metadata but lock file is missing.

### ISSUE THREAD

**Issue by anuprulez** [thoth-station/jupyterlab-requirements#233]
**Describe the bug**

Dependencies found in notebook metadata but lock file is missing

![jl_error](https://user-images.githubusercontent.com/3022518/112623274-70f8f080-8e2c-11eb-806f-e78a2c126ba5.png)

Does someone know why this could be an issue? It shows the error for every package I try to install

**Comment by pacospace** [comment]
> **Describe the bug**
> 
> Dependencies found in notebook metadata but lock file is missing
> 
> ![jl_error](https://user-images.githubusercontent.com/3022518/112623274-70f8f080-8e2c-11eb-806f-e78a2c126ba5.png)
> 
> Does someone know why this could be an issue? It shows the error for every package I try to install

Hi @anuprulez,

thanks for reaching out. Can you provide more information regarding the issue?

**Environment information**
Describe the environment from where you are using the extension:
 - jupyterlab-requirements version: [e.g. 0.5.0]
 - Installation source: [e.g. PyPI, from source, custom container image]
 - Operating system: [e.g. fedora32]
 - Environment type: [e.g. local installation or JupyterHub spawned image]

**Comment by anuprulez** [comment]
@pacospace Yes, I am using `jupyterlab-requirements` from inside a docker container (https://github.com/anuprulez/ml-jupyter-notebook/blob/galaxy-inte-docker-ml-jupyter/Dockerfile#L62). 
Docker's image has these details:

Jupyterlab: v3.0.9
jupyterlab-requirements version: 0.5.0
Installation source: Pip
OS: ubuntu2004
Environment type: From Jupyterlab

![jlr_install](https://user-images.githubusercontent.com/3022518/112632822-e8cd1800-8e38-11eb-9e03-0c2e1700884d.png)

Maybe there is some issue with installation? Thanks!

**Comment by pacospace** [comment]
> @pacospace Yes, I am using `jupyterlab-requirements` from inside a docker container (https://github.com/anuprulez/ml-jupyter-notebook/blob/galaxy-inte-docker-ml-jupyter/Dockerfile#L62).
> Docker's image has these details:
> 
> Jupyterlab: v3.0.9
> jupyterlab-requirements version: 0.5.0
> Installation source: Pip
> OS: ubuntu2004
> Environment type: From Jupyterlab
> Python: python3.8
> 
> ![jlr_install](https://user-images.githubusercontent.com/3022518/112632822-e8cd1800-8e38-11eb-9e03-0c2e1700884d.png)
> 
> Maybe there is some issue with installation? Thanks!

Thanks @anuprulez! I will have a look at this and come to you!

**Comment by pacospace** [comment]
> > @pacospace Yes, I am using `jupyterlab-requirements` from inside a docker container (https://github.com/anuprulez/ml-jupyter-notebook/blob/galaxy-inte-docker-ml-jupyter/Dockerfile#L62).
> > Docker's image has these details:
> > Jupyterlab: v3.0.9
> > jupyterlab-requirements version: 0.5.0
> > Installation source: Pip
> > OS: ubuntu2004
> > Environment type: From Jupyterlab
> > Python: python3.8
> > ![jlr_install](https://user-images.githubusercontent.com/3022518/112632822-e8cd1800-8e38-11eb-9e03-0c2e1700884d.png)
> > Maybe there is some issue with installation? Thanks!
> 
> Thanks @anuprulez! I will have a look at this and come back to you!

@anuprulez Do you have a link to a registry where I can pull that image and investigate?

**Comment by anuprulez** [comment]
@pacospace docker image: `anupkumar/docker-ml-jupyterlab:galaxy-integration`
Please note that it is a big docker image (>10GB in size).

**Comment by pacospace** [comment]
> @pacospace docker image: `anupkumar/docker-ml-jupyterlab:galaxy-integration`
> Please note that it is a big docker image (>10GB in size).

This is what I get for that image when trying to run it:
```

[I 2021-03-26 16:52:36.253 LabApp] JupyterLab application directory is /opt/conda/share/jupyter/lab
[W 16:52:37.371 NotebookApp] Error loading server extension jupyterlab_requirements
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/notebook/notebookapp.py", line 1988, in init_server_extensions
        mod = importlib.import_module(modulename)
      File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
      File "<frozen importlib._bootstrap>", line 991, in _find_and_load
      File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
      File "<frozen importlib._bootstrap_external>", line 783, in exec_module
      File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
      File "/opt/conda/lib/python3.8/site-packages/jupyterlab_requirements/__init__.py", line 24, in <module>
        from .dependency_management import DependenciesFilesHandler, PipenvHandler
      File "/opt/conda/lib/python3.8/site-packages/jupyterlab_requirements/dependency_management/__init__.py", line 19, in <module>
        from .dependencies_files_handler import DependenciesFilesHandler
      File "/opt/conda/lib/python3.8/site-packages/jupyterlab_requirements/dependency_management/dependencies_files_handler.py", line 28, in <module>
        from thamos.cli import _load_files
    ImportError: cannot import name '_load_files' from 'thamos.cli' (/opt/conda/lib/python3.8/site-packages/thamos/cli.py)
```
It is related to a new release of the transitive dependency of jupyterlab-requirements and we solved that issue already, you can use `thamos < 1.16.0` in your dependencies of the container as workaround.

Or use the new release I will create soon 0.6.0, that will solve the issue with: https://github.com/thoth-station/jupyterlab-requirements/pull/237/files.

**Comment by anuprulez** [comment]
@pacospace Ok, thanks a lot. I will try out this solution :)

**Comment by pacospace** [comment]
@anuprulez 0.6.0 is available https://pypi.org/project/jupyterlab-requirements/

**Comment by anuprulez** [comment]
@pacospace Now, I installed `jupyterlab-requirements==0.6.1` but getting the following error:
```
Uncaught exception POST /ipython/jupyterlab_requirements/thoth/resolution?1617004613492 (172.17.0.1)
    HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='POST', uri='/ipython/jupyterlab_requirements/thoth/resolution?1617004613492', version='HTTP/1.1', remote_ip='172.17.0.1')
    Traceback (most recent call last):
      File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
        result = await result
      File "/opt/conda/lib/python3.8/site-packages/jupyterlab_requirements/dependency_management/thoth.py", line 47, in post
        config: str = input_data["thoth_config"]
    KeyError: 'thoth_config'
```

**Comment by pacospace** [comment]
> @pacospace Now, I installed `jupyterlab-requirements==0.6.1` but getting the following error:
> 
> ```
> Uncaught exception POST /ipython/jupyterlab_requirements/thoth/resolution?1617004613492 (172.17.0.1)
>     HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='POST', uri='/ipython/jupyterlab_requirements/thoth/resolution?1617004613492', version='HTTP/1.1', remote_ip='172.17.0.1')
>     Traceback (most recent call last):
>       File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
>         result = await result
>       File "/opt/conda/lib/python3.8/site-packages/jupyterlab_requirements/dependency_management/thoth.py", line 47, in post
>         config: str = input_data["thoth_config"]
>     KeyError: 'thoth_config'
> ```

Hi @anuprulez,

thanks for reporting this. I will solve it and release patch soon!

**Comment by pacospace** [comment]
> > @pacospace Now, I installed `jupyterlab-requirements==0.6.1` but getting the following error:
> > ```
> > Uncaught exception POST /ipython/jupyterlab_requirements/thoth/resolution?1617004613492 (172.17.0.1)
> >     HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='POST', uri='/ipython/jupyterlab_requirements/thoth/resolution?1617004613492', version='HTTP/1.1', remote_ip='172.17.0.1')
> >     Traceback (most recent call last):
> >       File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
> >         result = await result
> >       File "/opt/conda/lib/python3.8/site-packages/jupyterlab_requirements/dependency_management/thoth.py", line 47, in post
> >         config: str = input_data["thoth_config"]
> >     KeyError: 'thoth_config'
> > ```
> 
> Hi @anuprulez,
> 
> thanks for reporting this. I will solve it and release patch soon!

@anuprulez I solved the issue above in 0.6.2 and found out another issue for missing pipenv in the image that was solved in 0.6.3 :) 

Please let me know if there are more issues!

**Comment by pacospace** [comment]
> > > @pacospace Now, I installed `jupyterlab-requirements==0.6.1` but getting the following error:
> > > ```
> > > Uncaught exception POST /ipython/jupyterlab_requirements/thoth/resolution?1617004613492 (172.17.0.1)
> > >     HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='POST', uri='/ipython/jupyterlab_requirements/thoth/resolution?1617004613492', version='HTTP/1.1', remote_ip='172.17.0.1')
> > >     Traceback (most recent call last):
> > >       File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1704, in _execute
> > >         result = await result
> > >       File "/opt/conda/lib/python3.8/site-packages/jupyterlab_requirements/dependency_management/thoth.py", line 47, in post
> > >         config: str = input_data["thoth_config"]
> > >     KeyError: 'thoth_config'
> > > ```
> > 
> > 
> > Hi @anuprulez,
> > thanks for reporting this. I will solve it and release patch soon!
> 
> @anuprulez I solved the issue above in 0.6.2 and found out another issue for missing pipenv in the image that was solved in 0.6.3 :)
> 
> Please let me know if there are more issues!

This requirement for thamos should not be necessary anymore: https://github.com/anuprulez/ml-jupyter-notebook/blob/7e2c44e7da364c59e28fb6851795efb8e72bb258/Dockerfile#L62

**Comment by pacospace** [comment]
hey @anuprulez, new version solved all issues you had? :)

**Comment by anuprulez** [comment]
@pacospace yes, the issue seems to be solved. Thanks a lot!!

**Comment by pacospace** [comment]
> @pacospace yes, the issue seems to be solved. Thanks a lot!!

Glad to hear that and thank you @anuprulez for reporting it!!!
