### ISSUE TITLE
When user ask for resolution with dependencies not available on PyPI both resolver fails, without giving more explanation beside opening issue with Thoth Team

### ISSUE THREAD

**Issue by oindrillac** [thoth-station/jupyterlab-requirements#270]
**Describe the bug**
Trying to add notebook specific dependencies as per https://github.com/thoth-station/jupyterlab-requirements#usage does not  seem to be working on JupyterLab.

**To Reproduce**
1. Go to https://jupyterhub-opf-jupyterhub.apps.zero.massopen.cloud/
2. Spawn Elyra 0.0.8 image
3. Open a notebook, such as [example](https://github.com/aicoe-aiops/ocp-ci-analysis/blob/master/notebooks/data-sources/TestGrid/metrics/get_raw_data.ipynb), and click on "Manage Dependencies".
4. Input kernel name eg : `get_raw_data` & "Install" pre-filled dependencies.
5. See error "Thoth resolution engine failed... pipenv will be used to lock dependencies!"

**Expected behavior**
Dependencies should have installed succesfully.

**Screenshots**

![image](https://user-images.githubusercontent.com/32435206/117707037-09a8bd00-b19c-11eb-9967-4f1eef35e785.png)
![image](https://user-images.githubusercontent.com/32435206/117707076-19c09c80-b19c-11eb-962e-775d8e7cbd32.png)

**Environment information**
Describe the environment from where you are using the extension:
 - jupyterlab version: 3.0.14
 - Environment type: JupyterLab Elyra Image 0.0.8

**Stack information**
If you have issue for resolving your stack with thoth resolution engine.
Please state the dependencies in your stack below.
* dotenv
* requests
* bs4
* ipynb

![image](https://user-images.githubusercontent.com/32435206/117707147-2f35c680-b19c-11eb-8b97-f071dadb0cf7.png)

cc @pacospace

**Comment by fridex** [comment]
It looks like packages you use do not exist. They are automatically detected based on imports, but sadly these imports do not correspond to package names in this case. Try to state the following packages:

```toml
[[source]]
url = "https://pypi.org/simple"
verify_ssl = true
name = "pypi"

[packages]
beautifulsoup4 = "*"
ipynb = "*"
python-dotenv = "*"
requests = "*"
```

I've tried with ubi:8+py3.6 and ubi:8+py3.8, the resolution looks good to me. Please let us know if the issue persists.

**Comment by fridex** [comment]
@pacospace I don't know how jupyterlab-requirements handles errors in such cases. It might be good to show users the resolution log and adviser id for traceability.

**Comment by oindrillac** [comment]
> It looks like packages you use do not exist. They are automatically detected based on imports, but sadly these imports do not correspond to package names in this case. Try to state the following packages:
> 
> ```toml
> [[source]]
> url = "https://pypi.org/simple"
> verify_ssl = true
> name = "pypi"
> 
> [packages]
> beautifulsoup4 = "*"
> ipynb = "*"
> python-dotenv = "*"
> requests = "*"
> ```
> 
> I've tried with ubi:8+py3.6 and ubi:8+py3.8, the resolution looks good to me. Please let us know if the issue persists.

@fridex yes, seems like the pre-fills dont correspond to the actual name. I will try to modify dotenv -> python-dotenv and bs4 -> beautifulsoup4 and follow the steps to see how its doing.

It might be useful to give a warning in such cases, where the package names are incorrect, something to alert the user that no package found with that name.

**Comment by oindrillac** [comment]
tried again, with the following 2 packages, and it seems to be stuck on the following screen

![image](https://user-images.githubusercontent.com/32435206/117715926-ef281100-b1a6-11eb-8617-e71b2d9aa757.png)

**Comment by fridex** [comment]
What recommendation type do you use? `stable` or `security` can take ~20 minutes to complete.

**Comment by oindrillac** [comment]
I'm on `latest` which is the default.

**Comment by pacospace** [comment]
> @pacospace I don't know how jupyterlab-requirements handles errors in such cases. It might be good to show users the resolution log and adviser id for traceability.

Problem is we fall back to pipenv, when adviser fails as we want to provide a resolution so they can continue working. But good to have when we will split the selection, so the user decide.
