### ISSUE TITLE
document user experience and configuration options wrt using Thoth Services

### ISSUE THREAD

**Issue by goern** [thoth-station/jupyterlab-requirements#275]
**Is your feature request related to a problem? Please describe.**
As a Data Scientist, I want to configure the extension, so that if the Thoth Service is unavailable, a fallback/local resolution is used.

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
n/a

/sig user-experience
/kind feature
/kind demo

**Comment by pacospace** [comment]
> **Is your feature request related to a problem? Please describe.**
> As a Data Scientist, I want to configure the extension, so that if the Thoth Service is unavailable, a fallback/local resolution is used.
> 
> **Describe the solution you'd like**
> n/a
> 
> **Describe alternatives you've considered**
> n/a
> 
> **Additional context**
> n/a
> 
> /sig user-experience
> /kind feature
> /kind demo

Thanks for opening this issue.

Currently, it is set to automatically fall back to `pipenv` if `thoth` fails. The issues we are getting are due to the processes handled from the frontend side and 500 gateway errors in the cluster. We are working on it.

**Comment by pacospace** [comment]
Related-To: https://github.com/thoth-station/jupyterlab-requirements/issues/62
