### ISSUE TITLE
can we do the dependency management in a cell?

### ISSUE THREAD

**Issue by goern** [thoth-station/jupyterlab-requirements#280]
**Is your feature request related to a problem? Please describe.**
As a Data Scientist, I want to add/remove/install the dependencies of my notebook via some command in a cell.

**Describe the solution you'd like**
n/a

**Describe alternatives you've considered**
n/a

**Additional context**
In addition to that, can we have a plugin that rewrites cells with `!pip install` so that a ... better way is ...

/kind feature
/triage needs-information

**Comment by pacospace** [comment]
Thank you very much for this feature request. We will plan to add it in next releases.

**Comment by pacospace** [comment]
Have a look at https://ipython.readthedocs.io/en/stable/config/custommagics.html

**Comment by goern** [comment]
@riekrh please have a look

**Comment by riekrh** [comment]
> @riekrh please have a look
Looks great. Maybe add the ability to harvest the existing !pip install lines as the input?

**Comment by pacospace** [comment]
> > @riekrh please have a look

Looks great. Maybe add the ability to harvest the existing !pip install lines as the input?

**Comment by pacospace** [comment]
Tasks
- [ ] Add logic to read cells that contains `!pip install lines` and extract packages to be added to notebook metadata as requirements (combined with invectio 1. when a notebook already exist and no dependencies are present, 2. when someone tries to use !pip install in the cell, sending a notification of what happened)
- [ ] Remove these cells from the notebook

**Comment by pacospace** [comment]
They can be done currently using `horus` CLI that will be available from v0.9.0:

![Screenshot from 2021-07-15 14-00-29](https://user-images.githubusercontent.com/27498679/125784704-5006d354-165e-4f0c-916e-09c76a4e0020.png)
![Screenshot from 2021-07-15 14-00-04](https://user-images.githubusercontent.com/27498679/125784712-452666c2-3b68-4560-924f-145687084c9d.png)


but there is an issue on having magic commands registered, that I opened upstream: https://github.com/ipython/ipython/issues/13061

**Comment by pacospace** [comment]
> **Is your feature request related to a problem? Please describe.**
> As a Data Scientist, I want to add/remove/install the dependencies of my notebook via some command in a cell.
> 
> **Describe the solution you'd like**
> n/a
> 
> **Describe alternatives you've considered**
> n/a
> 
> **Additional context**
> In addition to that, can we have a plugin that rewrites cells with `!pip install` so that a ... better way is ...
> 
> /kind feature
> /triage needs-information

Split the two requests: magic commands are for this issue. while rewriting cells:  https://github.com/thoth-station/jupyterlab-requirements/issues/357

**Comment by pacospace** [comment]
> They can be done currently using `horus` jupyterlab-requirments CLI that will be available from v0.9.0 (testing locally):
> 
> ![Screenshot from 2021-07-15 14-00-29](https://user-images.githubusercontent.com/27498679/125784704-5006d354-165e-4f0c-916e-09c76a4e0020.png)
> ![Screenshot from 2021-07-15 14-00-04](https://user-images.githubusercontent.com/27498679/125784712-452666c2-3b68-4560-924f-145687084c9d.png)
> 
> but there is an issue on having magic commands registered, that I opened upstream: [ipython/ipython#13061](https://github.com/ipython/ipython/issues/13061)

Solved issue upstream, now we can have magic commands:

![Screenshot from 2021-07-21 14-50-34](https://user-images.githubusercontent.com/27498679/126491430-9d79ff4c-aaff-43bd-8980-228f08544d9f.png)

**Comment by pacospace** [comment]
> > @riekrh please have a look
> > Looks great. Maybe add the ability to harvest the existing !pip install lines as the input?

new feature
![clean-pip-cells](https://user-images.githubusercontent.com/27498679/132551196-a5260155-0b63-4c63-9f32-d4e00c524534.gif)
