### ISSUE TITLE
Send a warning if the package detected is not available on PyPI

### ISSUE THREAD

**Issue by pacospace** [thoth-station/jupyterlab-requirements#315]
**Is your feature request related to a problem? Please describe.**
See: https://github.com/thoth-station/jupyterlab-requirements/issues/270

**Describe the solution you'd like**
Check in the background that verifies all packages detected exist on PyPI

**Describe alternatives you've considered**
Leave as it is, user needs to be sure those packages exist, otherwise, resolution engines will continue to fail. See: https://github.com/thoth-station/jupyterlab-requirements/issues/270

**Additional context**
See: https://github.com/thoth-station/thoth-application/issues/1280

**Comment by pacospace** [comment]
Fixed by: https://github.com/thoth-station/jupyterlab-requirements/pull/623 cc @Gkrumbach07 ?

**Comment by Gkrumbach07** [comment]
> Fixed by: #623 cc @Gkrumbach07 ?

Yes the banners will notify if the package is valid or not before the user installs the packages.
