### ISSUE TITLE
Enable installing packages stated in the notebook from CLI

### ISSUE THREAD

**Issue by fridex** [thoth-station/jupyterlab-requirements#324]
**Is your feature request related to a problem? Please describe.**

As a user of jupyterlab-requirements, I would like to have the ability to install packages without actually starting the notebook. For this case, I would like to run a CLI that will make sure dependencies stated in the notebook are installed. This feature can be reused when creating notebooks in project Meteor.

EDIT: this might be useful also for container image analyses when we can check what jupyter-notebooks are present in the container image and extract dependency information

**Describe the solution you'd like**

Provide a mechanism to install packages without actually running the notebook into the current environment.

**Comment by goern** [comment]
@fridex is https://github.com/thoth-station/jupyterlab-requirements/issues/280 similar? or could we reuse parts of each of the (to be done) implementations?

/kind feature
/triage needs-information

**Comment by fridex** [comment]
> @fridex is #280 similar? or could we reuse parts of each of the (to be done) implementations?

#280 talks about installing dependencies from within a running jupyter notebook, the issue discussed here is about providing a CLI interface to install dependencies. From design point of view, it might be good to extract dependency information (and other thoth related information) from a command line without actually spawning jupyterlab/jupyterhub:

```console
$ jupyterlab-requirements-cli --extract-pipfile notebook.ipynb --runtime-environment "training" > Pipfile
$ jupyterlab-requirements-cli --extract-pipfile-lock notebook.ipynb --runtime-environment "training" > Pipfile.lock
$ # pipenv install or micropipenv install
$ # extract also Thoth configuration file:
$ jupyterlab-requirements-cli --extract-thoth-config notebook.ipynb > .thoth.yaml
$ # thamos advise --runtime-environment "training"
```

That way we can reuse these parts in other components.

**Comment by pacospace** [comment]
> **Is your feature request related to a problem? Please describe.**
> 
> As a user of jupyterlab-requirements, I would like to have the ability to install packages without actually starting the notebook. For this case, I would like to run a CLI that will make sure dependencies stated in the notebook are installed. This feature can be reused when creating notebooks in project Meteor.

+1, we could use this a pre step to create all the kernels already for all the notebooks, so the user does not need to create kernels again for that experiment!

> 
> EDIT: this might be useful also for container image analyses when we can check what jupyter-notebooks are present in the container image and extract dependency information

+1, We can fail the build also because some notebooks do not have dependencies, or correct dependencies for that image?

> 
> **Describe the solution you'd like**
> 
> Provide a mechanism to install packages without actually running the notebook into the current environment.

**Comment by pacospace** [comment]
> > @fridex is #280 similar? or could we reuse parts of each of the (to be done) implementations?
> 
> #280 talks about installing dependencies from within a running jupyter notebook, the issue discussed here is about providing a CLI interface to install dependencies. From design point of view, it might be good to extract dependency information (and other thoth related information) from a command line without actually spawning jupyterlab/jupyterhub:
> 
> ```
> $ jupyterlab-requirements-cli --extract-pipfile notebook.ipynb --runtime-environment "training" > Pipfile
> $ jupyterlab-requirements-cli --extract-pipfile-lock notebook.ipynb --runtime-environment "training" > Pipfile.lock
> $ # pipenv install or micropipenv install
> $ # extract also Thoth configuration file:
> $ jupyterlab-requirements-cli --extract-thoth-config notebook.ipynb > .thoth.yaml
> $ # thamos advise --runtime-environment "training"
> ```
> 
> That way we can reuse these parts in other components.

It could be used, when jupyterlab-requirements is started but no kernel exist for the requirements present in the notebook

**Comment by pacospace** [comment]
> > @fridex is #280 similar? or could we reuse parts of each of the (to be done) implementations?
> 
> #280 talks about installing dependencies from within a running jupyter notebook, the issue discussed here is about providing a CLI interface to install dependencies. From design point of view, it might be good to extract dependency information (and other thoth related information) from a command line without actually spawning jupyterlab/jupyterhub:
> 
> ```
> $ jupyterlab-requirements-cli --extract-pipfile notebook.ipynb --runtime-environment "training" > Pipfile
> $ jupyterlab-requirements-cli --extract-pipfile-lock notebook.ipynb --runtime-environment "training" > Pipfile.lock
> $ # pipenv install or micropipenv install
> $ # extract also Thoth configuration file:
> $ jupyterlab-requirements-cli --extract-thoth-config notebook.ipynb > .thoth.yaml
> $ # thamos advise --runtime-environment "training"
> ```
> 
> That way we can reuse these parts in other components.

Maybe also `jupyterlab-requirements-cli --discover notebook.ipynb` to attempt to create Pipfile for the user using invectio :)

**Comment by pacospace** [comment]
Introduce CLI commands to manage dependencies in the notebook:

- [x] extract (pipfile, pipfile.lock and .thoth.yaml)
- [x] check (check if dependencies exist in a notebook)
- [x] create-kernel ( use dependencies in the notebook and create the kernel for running that notebook)
- [x] discover (rely on invectio to create a Pipfile)
- [ ] save (save dependencies content in the notebook)
- [ ] requirements (add package to Pipfile)
- [ ] resolve (use Thoth or pipnev)

All those commands could be run from a cell.

**Comment by pacospace** [comment]
![Screenshot from 2021-07-14 20-28-14](https://user-images.githubusercontent.com/27498679/125673778-a3adaa86-34bb-402d-9300-be8c5dc953ae.png)
 
cc @fridex! Thanks! not sure about the name of the cli, isn't it too long `jupyterlab-requirements-cli`? should we have a new name? wdyt?

**Comment by pacospace** [comment]
> ![Screenshot from 2021-07-14 20-28-14](https://user-images.githubusercontent.com/27498679/125673778-a3adaa86-34bb-402d-9300-be8c5dc953ae.png)
> 
> cc @fridex! Thanks! not sure about the name of the cli, isn't it too long `jupyterlab-requirements-cli`? `jl-deps-cli` also doesn't seem nice, should we have a new name? wdyt?

Horus :D
