### ISSUE TITLE
Resolver did not find any stack that would satisfy requirements .... given the time allocated

### ISSUE THREAD

**Issue by MichaelClifford** [thoth-station/jupyterlab-requirements#329]
**Describe the bug**
When I click "install" on the jupyterlab-requirments UI I get the following error in my pod logs:

`Response: ({'error': True, 'error_msg': 'Resolver did not find any stack that would satisfy requirements and stack characteristics given the time allocated - see https://thoth-station.ninja/j/no_stack',` 

I used the default 60 second timeout. and "latest" recommendation type

**To Reproduce**
1. Go to elyra-aidevsecops-tutorial/notebooks/training.ipynb
2. Click on 'Manage dependencies'
3. Click install
4. Go to your jupyterhub pod logs on the zero cluster and see the log message above. 

**Expected behavior**
Thoth resolves my software stack. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4494906/124321574-f4bd2a00-db4b-11eb-8080-f44e343fe4bd.png)

**Environment information**
Describe the environment from where you are using the extension:

Im on the elyra experimental image

**Stack information**
Tensorflow == *
numpy == *
matplotlib == *
boto3 == *

![image](https://user-images.githubusercontent.com/4494906/124321671-1a4a3380-db4c-11eb-9c5e-90e262448922.png)

**Comment by pacospace** [comment]
Thanks @MichaelClifford!! You should use jupyterlab-requirements >=v0.7.4? We solved many issues since the v0.6.5! Not sure if you got already the new image on ODH, cc @harshad16!

**Comment by pacospace** [comment]
This is expected behaviour of the system, when thoth fails, the resolution will be done by pipenv. In new jupyterlab-requirements v0.8.0, all these errors will be provided in the UI.

**Comment by pacospace** [comment]
> Thanks @MichaelClifford!! You should use jupyterlab-requirements >=v0.7.4? We solved many issues since the v0.6.5! Not sure if you got already the new image on ODH, cc @harshad16!

You can spawn `AICoE Elyra AIDevSecOps Tutorial Notebook Image` if you want to try latest changes of jl-req. the elyra experimental does not have new release yet.
