### ISSUE TITLE
UI says everything is installed and ready to use, running cells throws "ModuleNotFound" errors 

### ISSUE THREAD

**Issue by MichaelClifford** [thoth-station/jupyterlab-requirements#331]
**Describe the bug**
UI says everything is installed and ready to use, but running cells throws "ModuleNotFound" errors 

**To Reproduce**
1. Go to elyra-aidevsecops-tutorial/notebooks/download_dataset.ipynb
2. Click on "Manage Dependencies" 
3. See the following message: "Everything installed and ready to use!
Keep in mind no runtime environment is present in the notebook metadata.
Therefore your software stack might not be optimized for your environment."
4. Click "Cancel"
5. Run the first cell
6. See Error:
```---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-1-7f950b9888b2> in <module>
      1 import os
----> 2 import boto3
      3 import logging
      4 import pickle
      5 

ModuleNotFoundError: No module named 'boto3'
```

**Expected behavior**
UI identifies that the packages are not installed and allows me to install them. 

**Screenshots**
![image](https://user-images.githubusercontent.com/4494906/124322126-e8859c80-db4c-11eb-834a-81ebf63c7d18.png)

![image](https://user-images.githubusercontent.com/4494906/124322573-ac067080-db4d-11eb-8f5d-716c1871e8b6.png)

**Environment information**
Describe the environment from where you are using the extension:

Elyra experimental image

**Stack information**

tensorflow==*
boto3==*
matplotlib==*

**Comment by pacospace** [comment]
Thanks @MichaelClifford! Please check: https://github.com/thoth-station/jupyterlab-requirements/issues/329#issuecomment-873311893

**Comment by goern** [comment]
/assign @pacospace 
/priority critical-urgent
/kind bug

see https://github.com/thoth-station/core/issues/294

**Comment by pacospace** [comment]
This error is not present in new jupyterlab-requirements >= 0.7.4. You can spawn `AICoE Elyra AIDevSecOps Tutorial Notebook Image` if you want to try latest changes of jl-req with this tutorial. the elyra experimental does not point to latest of s2i-lab-elyra as I thought, we need to open a PR on operate first to change that behaviour.

**Comment by pacospace** [comment]
> Thanks @MichaelClifford, I will look into this issue!!
> 
> NOTE: the elyra experimental on Operate First does not point to latest of s2i-lab-elyra as I thought but to a precise tag, we need to open a PR on operate first to change that behaviour.

Found the bug, we will make sure to have `>=0.8.0` in next release of s2i-lab-elyra image.
