### ISSUE TITLE
present extension at all ODSC conferences

### ISSUE THREAD

**Issue by goern** [thoth-station/jupyterlab-requirements#342]
**Is your feature request related to a problem? Please describe.**
As an action to get some attention to our work, we want to present the extension and how dependency management for jupyter notebooks is done at all the ODSC conferences.

ODSC West Round Two Deadline for Speaker Proposals Closes – August 29, 2021

Red Hat is a Partner of ODSC West.

**Describe the solution you'd like**
Host a session at ODSC West ;)

**Comment by pacospace** [comment]
@goern I got accepted and will host a session at ODSC West 2021 :)

**Comment by pacospace** [comment]
ODSC West material for Reproducibility and Dependencies for Jupyter Notebooks.

Slide: https://github.com/thoth-station/talks/blob/master/2021-11-16-odsc-west/ODSC%20West%202021.pdf
Recording: https://youtu.be/FvVJNccTibs

We can close the issue! We will track new submissions to a conference here: https://github.com/orgs/AICoE/projects/5
