### ISSUE TITLE
Having issues running horus from cli

### ISSUE THREAD

**Issue by oindrillac** [thoth-station/jupyterlab-requirements#363]
**Describe the bug**
I have installed jupyterlab-requirements locally and I am on version 0.9.2

When I run horus, I see that it is installed

```
% horus
Usage: horus [OPTIONS] COMMAND [ARGS]...

  Horus: CLI for jupyterlab-requirements.

Options:
  -v, --verbose  Be verbose about what's going on.
  --help         Show this message and exit.

Commands:
  check         Check dependencies in notebook metadata.
  discover      Discover dependencies from notebook content.
  extract       Extract dependencies from notebook metadata.
  lock          Lock requirements in notebook metadata.
  requirements  Add/Remove one or multiple requirements from the notebook.
  save          Save dependencies in notebook metadata.
  set-kernel    Create kernel using dependencies in notebook metadata.
  show          Show dependencies from notebook metadata.
  version       Print Horus, Thamos and Thoth version and exit.

```

When I run horus check on a notebook, I get an error
```
 % horus check download_dataset.ipynbTraceback (most recent call last):
  File "/Users/oindrillachatterjee/Library/Python/3.8/bin/horus", line 8, in <module>
    sys.exit(cli())
  File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/jupyterlab_requirements/cli.py", line 833, in check
    result = check_metadata_content(notebook_metadata=notebook_metadata)
  File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/jupyterlab_requirements/cli.py", line 780, in check_metadata_content
    kernel_packages = get_packages(kernel_name=kernel_name)
  File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/jupyterlab_requirements/dependency_management/lib.py", line 89, in get_packages
    process_output = subprocess.run(
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/Users/oindrillachatterjee/.local/share/thoth/kernels')
```

Do I need to install something that I am missing out?

**Environment information**
Describe the environment from where you are using the extension:
 - jupyterlab version: 4.0.0a1
 - jupyterlab-requirements version: 0.9.2
 - Installation source: PyPI
 - Operating system: MacOS

**Comment by pacospace** [comment]
> **Describe the bug**
> I have installed jupyterlab-requirements locally and I am on version 0.9.2
> 
> When I run horus, I see that it is installed
> 
> ```
> % horus
> Usage: horus [OPTIONS] COMMAND [ARGS]...
> 
>   Horus: CLI for jupyterlab-requirements.
> 
> Options:
>   -v, --verbose  Be verbose about what's going on.
>   --help         Show this message and exit.
> 
> Commands:
>   check         Check dependencies in notebook metadata.
>   discover      Discover dependencies from notebook content.
>   extract       Extract dependencies from notebook metadata.
>   lock          Lock requirements in notebook metadata.
>   requirements  Add/Remove one or multiple requirements from the notebook.
>   save          Save dependencies in notebook metadata.
>   set-kernel    Create kernel using dependencies in notebook metadata.
>   show          Show dependencies from notebook metadata.
>   version       Print Horus, Thamos and Thoth version and exit.
> ```
> 
> When I run horus check on a notebook, I get an error
> 
> ```
>  % horus check download_dataset.ipynbTraceback (most recent call last):
>   File "/Users/oindrillachatterjee/Library/Python/3.8/bin/horus", line 8, in <module>
>     sys.exit(cli())
>   File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/click/core.py", line 829, in __call__
>     return self.main(*args, **kwargs)
>   File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/click/core.py", line 782, in main
>     rv = self.invoke(ctx)
>   File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1259, in invoke
>     return _process_result(sub_ctx.command.invoke(sub_ctx))
>   File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1066, in invoke
>     return ctx.invoke(self.callback, **ctx.params)
>   File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/click/core.py", line 610, in invoke
>     return callback(*args, **kwargs)
>   File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/click/decorators.py", line 21, in new_func
>     return f(get_current_context(), *args, **kwargs)
>   File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/jupyterlab_requirements/cli.py", line 833, in check
>     result = check_metadata_content(notebook_metadata=notebook_metadata)
>   File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/jupyterlab_requirements/cli.py", line 780, in check_metadata_content
>     kernel_packages = get_packages(kernel_name=kernel_name)
>   File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/jupyterlab_requirements/dependency_management/lib.py", line 89, in get_packages
>     process_output = subprocess.run(
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
>     with Popen(*popenargs, **kwargs) as process:
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
>     self._execute_child(args, executable, preexec_fn, close_fds,
>   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
>     raise child_exception_type(errno_num, err_msg, err_filename)
> FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/Users/oindrillachatterjee/.local/share/thoth/kernels')
> ```
> 
> Do I need to install something that I am missing out?
> 
> **Environment information**
> Describe the environment from where you are using the extension:
> 
> * jupyterlab version: 4.0.0a1
> * jupyterlab-requirements version: 0.9.2
> * Installation source: PyPI
> * Operating system: MacOS

Thanks for opening this issue @oindrillac. Unfortunately I never saw this error on Linux tbh and I cannot replicate  MacOS :( 

But, in theory if that path does not exist, it should be created automatically. 
I will try to replicate that behaviour deleting the repo `.local/share/thoth/kernels` and running `%horus check`.

**Comment by pacospace** [comment]
> > **Describe the bug**
> > I have installed jupyterlab-requirements locally and I am on version 0.9.2
> > When I run horus, I see that it is installed
> > ```
> > % horus
> > Usage: horus [OPTIONS] COMMAND [ARGS]...
> > 
> >   Horus: CLI for jupyterlab-requirements.
> > 
> > Options:
> >   -v, --verbose  Be verbose about what's going on.
> >   --help         Show this message and exit.
> > 
> > Commands:
> >   check         Check dependencies in notebook metadata.
> >   discover      Discover dependencies from notebook content.
> >   extract       Extract dependencies from notebook metadata.
> >   lock          Lock requirements in notebook metadata.
> >   requirements  Add/Remove one or multiple requirements from the notebook.
> >   save          Save dependencies in notebook metadata.
> >   set-kernel    Create kernel using dependencies in notebook metadata.
> >   show          Show dependencies from notebook metadata.
> >   version       Print Horus, Thamos and Thoth version and exit.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > When I run horus check on a notebook, I get an error
> > ```
> >  % horus check download_dataset.ipynbTraceback (most recent call last):
> >   File "/Users/oindrillachatterjee/Library/Python/3.8/bin/horus", line 8, in <module>
> >     sys.exit(cli())
> >   File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/click/core.py", line 829, in __call__
> >     return self.main(*args, **kwargs)
> >   File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/click/core.py", line 782, in main
> >     rv = self.invoke(ctx)
> >   File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1259, in invoke
> >     return _process_result(sub_ctx.command.invoke(sub_ctx))
> >   File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/click/core.py", line 1066, in invoke
> >     return ctx.invoke(self.callback, **ctx.params)
> >   File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/click/core.py", line 610, in invoke
> >     return callback(*args, **kwargs)
> >   File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/click/decorators.py", line 21, in new_func
> >     return f(get_current_context(), *args, **kwargs)
> >   File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/jupyterlab_requirements/cli.py", line 833, in check
> >     result = check_metadata_content(notebook_metadata=notebook_metadata)
> >   File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/jupyterlab_requirements/cli.py", line 780, in check_metadata_content
> >     kernel_packages = get_packages(kernel_name=kernel_name)
> >   File "/Users/oindrillachatterjee/Library/Python/3.8/lib/python/site-packages/jupyterlab_requirements/dependency_management/lib.py", line 89, in get_packages
> >     process_output = subprocess.run(
> >   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 489, in run
> >     with Popen(*popenargs, **kwargs) as process:
> >   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 854, in __init__
> >     self._execute_child(args, executable, preexec_fn, close_fds,
> >   File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/subprocess.py", line 1702, in _execute_child
> >     raise child_exception_type(errno_num, err_msg, err_filename)
> > FileNotFoundError: [Errno 2] No such file or directory: PosixPath('/Users/oindrillachatterjee/.local/share/thoth/kernels')
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Do I need to install something that I am missing out?
> > **Environment information**
> > Describe the environment from where you are using the extension:
> > 
> > * jupyterlab version: 4.0.0a1
> > * jupyterlab-requirements version: 0.9.2
> > * Installation source: PyPI
> > * Operating system: MacOS
> 
> Thanks for opening this issue @oindrillac. Unfortunately I never saw this error on Linux tbh and I cannot replicate MacOS :(
> 
> But, in theory if that path does not exist, it should be created automatically.
> I will try to replicate that behaviour deleting the repo `.local/share/thoth/kernels` and running `%horus check`.

I was able to replicate that, that path exists already on my machine, that is why I didn't find that while introducing horus :) Thanks for spotting this, I will create a patch for that 🚀

**Comment by oindrillac** [comment]
thanks for looking into this @pacospace
