### ISSUE TITLE
recommendation from Thoth fails because base image discovered filters out packages not present in the discovered base image

### ISSUE THREAD

**Issue by pacospace** [thoth-station/jupyterlab-requirements#544]
**Describe the bug**
recommendation from Thoth fails because based image discovered filters out packages not present in the known base image

**To Reproduce**
1. `podman run -p 8888:8888 quay.io/thoth-station/s2i-lab-elyra:latest start-singleuser.sh --ip="0.0.0.0" --port=8888`
2. start a new notebook
3. Run %horus requirements --add pandas
4. Run %horus lock 

**Expected behavior**
Horus lock correctly provide recommendation using thoth resolver.

**Screenshots**
```
Exception("Cannot satisfy direct dependencies: direct dependencies of type 'pandas' were removed by pipeline sieves")
```

**Environment information**
 - jupyterlab-requirements version: latest

**Stack information**
pandas from PyPI

**Additional context**

**Comment by pacospace** [comment]
> From the description, it is not clear to me what's happening. Could you post adviser id for the resolution request?

It's an issue in jupyterlab-requirements when giving the requirements input to thamos library:

adviser-211020162604-ed2c3d945003c20c scheduled from jupyterlab-requirements
```
    "requirements": "{\"packages\":{\"pandas\":\"*\"},\"dev-packages\":{},\"source\":[{\"url\":\"https://pypi.org/simple\",\"verify_ssl\":true,\"name\":\"pypi\"}],\"requires\":{\"python_version\":\"3.8\"}}",

```

adviser-211020161426-a4f675ba0629d83b scheduled from thamos CLI
```
    "requirements": "[[source]]\nurl = \"https://pypi.org/simple\"\nverify_ssl = true\nname = \"pypi\"\n\n[packages]\npandas = \"*\"\n\n[dev-packages]\n\n[requires]\npython_version = \"3.8\"\n",
```

I'm implementing a workaround.

**Comment by fridex** [comment]
It is still not clear to me what's happening here. It looks like both requirements are equivalent - one uses TOML, the other one uses JSON. The backend should treat both cases as valid (and equivalent) inputs.

**Comment by pacospace** [comment]
> > > > ```
> > > > "base_image": "quay.io/thoth-station/s2i-lab-elyra:v0.0.13",
> > > > ```
> > > 
> > > 
> > > or it has to do with the base image?
> > 
> > 
> > Could be, could you try to run without `base_image` stated?
> 
> It is automatically discovered actually, so the user cannot remove it at the moment. I have to trigger it manually.

It was the base image actually @fridex, not the requirements!

**Comment by fridex** [comment]
This should be fixed with the referenced PRs. Feel free to reopen if the issue persists.

/close
