### ISSUE TITLE
Every tables on jupyterlab affected by thoth station css

### ISSUE THREAD

**Issue by arielshulman** [thoth-station/jupyterlab-requirements#559]
**Describe the bug**
We're using s2i-minimal-notebook project in our openshift environment as our base image for ml models development.
We've gladly found thoth-station new versions for the s2i-minimal-notebook and we've decide to test it for our work.
Everything worked fine but we've found strange behavior with pandas tables "display" cells, which look differently since before. After some digging we've found a [CSS entry](https://github.com/thoth-station/jupyterlab-requirements/blob/8165bcf092a963b4f9c0be5ccc30a0636ba40fbe/style/index.css#L106-L108)  which direct tables to 100% width which was part of the jupyterlab-requierments plugin.

**To Reproduce**
1. Open jupyterlab
2. Import pandas table
3. display the dataframe

**Expected behavior**
Dataframe table (no any table on jupyterlab) should not be affected visually after installing jupyterlab-requierments

**Screenshots**
![image](https://user-images.githubusercontent.com/15850184/140289923-d886b57f-3669-4534-8827-20d94ddf1ac3.png)
instead of this
![image](https://user-images.githubusercontent.com/15850184/140290827-6bae16f1-f833-477a-b623-bd3ebee48051.png)

**Environment information**
Describe the environment from where you are using the extension:
 - jupyterlab version: 3.2.1
 - jupyterlab-requirements version: 0.8.0
 - Environment type: thoth-station/s2i-minimal-py38-notebook
 - quay.io/thoth-station/s2i-minimal-py38-notebook:v0.1.2

**Additional context**
My computer is in RTL, which may affect the oreintation of the table.

**Comment by pacospace** [comment]
> **Describe the bug** We're using s2i-minimal-notebook project in our openshift environment as our base image for ml models development. We've gladly found thoth-station new versions for the s2i-minimal-notebook and we've decide to test it for our work. Everything worked fine but we've found strange behavior with pandas tables "display" cells, which look differently since before. After some digging we've found a [CSS entry](https://github.com/thoth-station/jupyterlab-requirements/blob/8165bcf092a963b4f9c0be5ccc30a0636ba40fbe/style/index.css#L106-L108) which direct tables to 100% width which was part of the jupyterlab-requierments plugin.
> 
> **To Reproduce** Steps to reproduce the behavior:
> 
> 1. Open jupyterlab
> 2. Import pandas table
> 3. display the dataframe
> 
> **Expected behavior** Dataframe table (no any table on jupyterlab) should not be affected visually after installing jupyterlab-requierments
> 
> **Screenshots** ![image](https://user-images.githubusercontent.com/15850184/140289923-d886b57f-3669-4534-8827-20d94ddf1ac3.png) instead of this ![image](https://user-images.githubusercontent.com/15850184/140290827-6bae16f1-f833-477a-b623-bd3ebee48051.png)
> 
> **Environment information** Describe the environment from where you are using the extension:
> 
> * jupyterlab version: 3.2.1
> * jupyterlab-requirements version: 0.8.0
> * Environment type: thoth-station/s2i-minimal-py38-notebook
> * quay.io/thoth-station/s2i-minimal-py38-notebook:v0.1.2
> 
> **Additional context** My computer is in RTL, which may affect the oreintation of the table.

hey @arielshulman thanks for reporting this issue. I was able to replicate it. I will adjust it and include the fix in the next release `v0.13.0`

**Comment by arielshulman** [comment]
@pacospace Thank you for the super quick response!
Just a thought, maybe the CSS selectors should be more strict and not to include all of the th, tr, table globaly.
Although the impact could be less noticed, it seems there are more potential global impacts by the CSS, like in this selector:

https://github.com/thoth-station/jupyterlab-requirements/blob/a9df8c06bc0b2634ec3add178619d4388d48e8b9/style/index.css#L106-L108

**Comment by pacospace** [comment]
> @pacospace Thank you for the super quick response! Just a thought, maybe the CSS selectors should be more strict and not to include all of the th, tr, table globaly. Although the impact could be less noticed, it seems there are more potential global impacts by the CSS, like in this selector:
> 
> https://github.com/thoth-station/jupyterlab-requirements/blob/a9df8c06bc0b2634ec3add178619d4388d48e8b9/style/index.css#L106-L108

Thanks @arielshulman! Do you want to contribute with some fixes here? the UX part need some improvements for sure :)

**Comment by arielshulman** [comment]
Sorry, but my I'm far from being  UI/UX guy 😔
