### ISSUE TITLE
Parameters requested from the UI once selected do not modify the state

### ISSUE THREAD

**Issue by pacospace** [thoth-station/jupyterlab-requirements#599]
**Describe the bug**
Parameters requested from the UI once selected do not modify the state of the app.

**To Reproduce**
1. Open UI and select Pipenv as the resolution engine for example or try to select any of the other parameters

**Expected behavior**

**Screenshots**

**Environment information**
current master of jupyterlab-requirements

**Stack information**

**Additional context**

**Comment by Gkrumbach07** [comment]
There were a few issues, but I think I fixed them.
