### ISSUE TITLE
Improve OPTIONS UI for dependency resolvers

### ISSUE THREAD

**Issue by pacospace** [thoth-station/jupyterlab-requirements#609]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Improve quality of UI options for dependency resolvers

**Describe alternatives you've considered**

**Additional context**

**Comment by Gkrumbach07** [comment]
Hi @pacospace, When you say quality, do you mean the visual aspect or a interaction aspect of the UI. Are you suggesting a complete overhaul or slight tweaks.

Does the new UI in https://github.com/thoth-station/jupyter-nbrequirements#nbrequirements-ui look like something you would want in a UI upgrade?

**Comment by pacospace** [comment]
> Hi @pacospace, When you say quality, do you mean the visual aspect or a interaction aspect of the UI. Are you suggesting a complete overhaul or slight tweaks.
> 
> Does the new UI in https://github.com/thoth-station/jupyter-nbrequirements#nbrequirements-ui look like something you would want in a UI upgrade?

hey @Gkrumbach07, thank you for asking. I'm interested in the visual aspect for the OPTIONS part of the UI.

Moving into the direction of nbrequirements look would be nice indeed I think, but if you have better option feel free to propose :)

**Comment by Gkrumbach07** [comment]
Any changes / concerns / issues you see with this implantation @pacospace?

https://user-images.githubusercontent.com/12587674/153674654-537e8c08-70ce-4225-8376-02072ea14390.mov

n

**Comment by pacospace** [comment]
> Any changes / concerns / issues you see with this implantation @pacospace?
> 
>  Screen.Recording.2022-02-11.at.3.43.44.PM.mov 
> n

This is great @Gkrumbach07!
