### ISSUE TITLE
[2pt] plugin is unable to send request to Thoth engine

### ISSUE THREAD

**Issue by harshad16** [thoth-station/jupyterlab-requirements#625]
**Describe the bug**
The plugin is failing to send the locking request to Project Thoth, as it is not updated with the latest user-api changes
it is still sending the same parameters, and causing extra parameter issues.
`Extra query parameter(s) count not in spec",\n  "status": 400`

The count parameter was removed in v0.35.2:
https://github.com/thoth-station/user-api/commit/1615c40699c204825cb087640cf66569def22367

**To Reproduce**
1. Go to 'any notebook'
2. execute the dependency management with plugin
3. See error

**Expected behavior**
Work without issue

**Screenshots**
```
%horus lock
Exception('Error locking dependencies, check pod logs for more details about the error. (400)\nReason: BAD REQUEST\nHTTP response headers: HTTPHeaderDict({\'server\': \'gunicorn\', \'date\': \'Tue, 14 Jun 2022 06:00:38 GMT\', \'content-type\': \'application/problem+json\', \'content-length\': \'120\', \'access-control-allow-origin\': \'*\', \'x-thoth-version\': \'0.35.2\', \'x-user-api-service-version\': \'0.35.2+messaging.0.16.1.storages.0.72.1.common.0.36.2.python.0.16.10\', \'x-thoth-search-ui-url\': \'[https://thoth-station.ninja/search/\](https://thoth-station.ninja/search//)', \'set-cookie\': \'99770cb82864be05282857f803e02327=71283d09b941169601817f89b67f6781; path=/; HttpOnly; Secure; SameSite=None\'})\nHTTP response body: {\n  "detail": "Extra query parameter(s) count not in spec",\n  "status": 400,\n  "title": null,\n  "type": "about:blank"\n}\n\n')
```

**Environment information**
Describe the environment from where you are using the extension:
 - jupyterlab version:  3.1.14
 - jupyterlab-requirements version:  0.11.0

**Comment by codificat** [comment]
/priority critical-urgent
/assign @Gkrumbach07 
as this is a similar fix to what was fixed in the search UI
/triage accepted
