### ISSUE TITLE
Introduce auto completion and dropdown for package name and constraint

### ISSUE THREAD

**Issue by pacospace** [thoth-station/jupyterlab-requirements#63]
**Is your feature request related to a problem? Please describe.**
As User of jupyterlab-requirements UI,

I would like to have autocompletion when I start typing the name of a package. When a package is selected I want to have dropdown will have versions available of that package.

**Describe the solution you'd like**
See jupyter-nbrequirements for the idea: https://github.com/thoth-station/jupyter-nbrequirements

**Describe alternatives you've considered**

**Additional context**

**Comment by pacospace** [comment]
Related-To: https://github.com/thoth-station/jupyterlab-requirements/issues/270

- [ ] Verify name of the package exist on certain index otherwise send warning to user

**Comment by Gkrumbach07** [comment]
Will the version dropdown take the place of the constraint text box? I can see there being two dropdown, one for the condition (==, >, <, etc), and one for the actual version.

**Comment by pacospace** [comment]
> Will the version dropdown take the place of the constraint text box? I can see there being two dropdown, one for the condition (==, >, <, etc), and one for the actual version.

Sounds better to have one for condition and one for version yes, thanks @Gkrumbach07, then we will need one for the index:  https://github.com/thoth-station/jupyterlab-requirements/issues/232

**Comment by pacospace** [comment]
Please assign to yourself the issue @Gkrumbach07 if you start to work on it and put the lifecycle active label also :) Thanks!! 🚀

**Comment by Gkrumbach07** [comment]
No simple way to "search" for a package ( i.e. `pand` -> `pandas` ) but I am able to give an indication when a package is valid.

![image](https://user-images.githubusercontent.com/12587674/152037679-3ee05887-1e06-4272-b228-d74db461316d.png)
vs
![image](https://user-images.githubusercontent.com/12587674/152037779-d32c9c38-3d6b-465d-a506-0d9db88b56aa.png)

**Comment by pacospace** [comment]
> No simple way to "search" for a package ( i.e. `pand` -> `pandas` ) but I am able to give an indication when a package is valid.
> 
> ![image](https://user-images.githubusercontent.com/12587674/152037679-3ee05887-1e06-4272-b228-d74db461316d.png) vs ![image](https://user-images.githubusercontent.com/12587674/152037779-d32c9c38-3d6b-465d-a506-0d9db88b56aa.png)

This is really awesome!! Thanks @Gkrumbach07!

**Comment by Gkrumbach07** [comment]
Version picker is complete. It is a bit more complex due to needing to have multiple constraints. Let me know if it needs tweaking

https://user-images.githubusercontent.com/12587674/152221658-7277530c-3b38-4233-982b-648b134b4447.mov

**Comment by pacospace** [comment]
> Version picker is complete. It is a bit more complex due to needing to have multiple constraints. Let me know if it needs tweaking
> 
>  clip-demo.mov

Very nice!! Thanks @Gkrumbach07, can we show the description of the package entirely?

also can we show the releases in reversed order, from latest to oldest?

I love the multiple constraints option!!

**Comment by goern** [comment]
any updates on this? do we consider it done?

**Comment by Gkrumbach07** [comment]
It is in the latest release. Can be closed.
