### ISSUE TITLE
Not to use pip module prompt is being sent on each instance

### ISSUE THREAD

**Issue by harshad16** [thoth-station/jupyterlab-requirements#630]
**Describe the bug**
Users are facing with huge volume of prompt to not use pip, lets reduce these prompt message to one
Further discuss: https://chat.google.com/room/AAAAVjnVXFk/cY0DMXbRtIU
![image](https://user-images.githubusercontent.com/14028058/175562336-318c23cd-947e-4026-8f39-9e4656391a08.png)

**To Reproduce**
1. Go to notebook
2. type `pip install in cell`
3. See error

**Expected behavior**
See the prompt once

**Comment by Gkrumbach07** [comment]
/close
confirmed working in latest release
